objects:
  - type: sphere
    center: [0.0, 0.0, 3.0]
    radius: 0.2
    density: 1.0

rod:
  n_elem: 20
  start: [0.0, 0.0, 0.0]
  direction: [0.0, 0.0, 1.0]
  normal: [0.0, 1.0, 0.0]
  base_length: 1.0
  base_radius: 0.025
  density: 1000
  youngs_modulus: 10000000
  poisson_ratio: 0.5

# Simulator configuration
simulator:
  final_time: 11.01
  time_step: 5.0e-5
  collect_data: true
  rendering_fps: 100
  update_interval: 1
