objects:

rod:
  n_elem: 20
  start: [0.0, 0.0, 0.0]
  direction: [0.0, 0.0, 1.0]
  normal: [0.0, 1.0, 0.0]
  base_length: 0.5
  base_radius: 0.025
  density: 1000
  youngs_modulus: 10000000
  poisson_ratio: 0.5

# Simulator configuration
simulator:
  final_time: 5.00
  time_step: 5.0e-5
  collect_data: true
  rendering_fps: 15
  update_interval: 1
