# Sphere configuration
objects:
  - type: sphere
    center: [-0.43992845,  0.56807642,  0.15406894]
    radius: 0.05
    density: 1000.0
    color: ""

  - type: sphere
    center: [-0.3838272, -0.18255463, 0.08664133]
    radius: 0.01
    density: 1000.0
    color: ""


# rod configuration
rod:
  n_elem: 20
  start: [0.0, 0.0, 0.0]
  direction: [0.0, 0.0, 1.0]
  normal: [1.0, 0.0, 0.0]
  base_length: 1.0
  base_radius: 0.05
  density: 1000
  youngs_modulus: 10000000.0
  poisson_ratio: 0.5

# Simulator configuration
simulator:
  final_time: 5.0
  time_step: 2.0e-4
  collect_data: true
  rendering_fps: 60
  update_interval: 7

# controller configuration
controller:
  trainable: false
  number_of_control_points: 6
  obs_state_points: 10
