# Sphere configuration
sphere:
  center: [-0.4, -0.5, 0.2]
  radius: 0.05
  density: 1000.0
  direction: [0.0, 30.0, 0.0]

rod:
  n_elem: 20
  start: [0.0, 0.0, 0.0]
  direction: [0.0, 0.0, 1.0]
  normal: [1.0, 0.0, 0.0]
  base_length: 1.0
  base_radius: 0.05
  density: 1000
  youngs_modulus: 10000000
  poisson_ratio: 0.5

# Simulator configuration
simulator:
  final_time: 2.0
  time_step: 2.0e-4
  collect_data: true
  rendering_fps: 60
  update_interval: 7

controller:
  trainable: false #true
  number_of_control_points: 6
  obs_state_points: 10
  boundary: [-0.3, 0.3, -0.3, 0.3, 0.4, 0.5]
