# Sphere configuration
objects:
  # - type: sphere
  #   center: [2.0, 0.0, 0.3]
  #   radius: 0.3
  #   density: 1.0
  # - type: sphere
  #   center: [3.2, -1.8, 0.3]
  #   radius: 0.3
  #   density: 1.0
  # - type: sphere
  #   center: [1.8, -3.5, 0.3]
  #   radius: 0.3
  #   density: 1.0
  - type: sphere
    center: [0.40741026108987037, -0.1671957213830692, 0.16156895806419683]
    radius: 0.05
    density: 1000

# Rod configuration
rod:
  n_elem: 20
  start: [0.0, 0.0, 0.0]
  direction: [0.0, 0.0, 1.0]
  normal: [0.0, 1.0, 0.0]
  base_length: 1.0
  radius_tip: 0.05
  base_radius: 0.05
  density: 1000
  youngs_modulus: 1e7
  poisson_ratio: 0.5

# Simulator configuration
simulator:
  final_time: 2
  time_step: 2.0e-4
  collect_data: true
  rendering_fps: 30
  update_interval: 7

# Controller configuration
controller:
  trainable: false
  number_of_control_points: 6
  obs_state_points: 10


