# Sphere configuration
objects:
  - type: sphere
    center: [2, 0.0, 0.3]
    radius: 0.3
    density: 1.0
  # - type: mesh_surface
  #   mesh_path: /data/zyw/workshop/PyElastica/tests/cube.stl
  #   center: [0.0, 0.0, 3.0]
  - type: sphere
    center: [0, 2, 0.3]
    radius: 0.3
    density: 1.0
  - type: sphere
    center: [3.2, -1.8, 0.35]
    radius: 0.35
    density: 1.0
  - type: sphere
    center: [-2.5, 3.0, 0.5]
    radius: 0.5
    density: 1.0
  - type: sphere
    center: [1.8, -3.5, 0.4]
    radius: 0.4
    density: 1.0
rod:
  n_elem: 50
  start: [0.0, 0.0, 0.0]
  direction: [0.0, 0.0, 1.0]
  normal: [0.0, 1.0, 0.0]
  base_length: 2
  base_radius: 0.0035
  density: 100000
  youngs_modulus: 1000000
  poisson_ratio: 0.5

# Simulator configuration
simulator:
  final_time: 10.0
  time_step: 2.5e-4
  collect_data: true
  rendering_fps: 20
  update_interval: 2
